- kernel/interrupt.rs
Fixes #29 
I have very little knowledge of how OS should work, but some parts of IRQ handlers do not feel right.
Here
https://github.com/Lurk/kerla/blob/b213c965d3127a35b429da62fa9d134304107fbf/kernel/interrupt.rs#L28-L31
we do not check if the handler is already assigned. That will definitely lead to strange bugs. 
And here 
https://github.com/Lurk/kerla/blob/b213c965d3127a35b429da62fa9d134304107fbf/kernel/interrupt.rs#L33-L38
The call of net::process_packets feels like it should be done in the handler.
If I am right, should I tackle it in this pull request or create separate issues and pull requests?
> ISSUE-29: Switch IRQ handler's map from BTreeMap to array

- kernel/interrupt.rs
We must ensure that the registered IRQ handler is not rewriten by another attach_irq call.
> panic if handler for specific IRQ is already attached

- kernel/boot.rs
- kernel/interrupt.rs
I know @Lurk PRed his fix for #29 and it was approved, but this is suggestion how to avoid conditional branching in the interrupt handler. It doesn't panic if the handler is already set yet, but can be added.
You may like it or not, I don't mind if you reject this PR.
Coming from the embedded work first thing that struck me was how to make interrupt handler as efficient as possible; I have even rough idea how to avoid `Box<>` in the array, but that's more work I don't have time for at the moment: we could only keep array of references to trait implementation, and static instances holding particular interrupt handler - if done right it wouldn't even need to panic, assuming IRQ# assignment at compile time is acceptable for all cases.
> [ISSUE-29] IRQ handlers with no conditional branching

- kernel/process/fork.rs
- kernel/process/process.rs
Fixes #42 by removing unnecessary indirection of the `Option<Weak<>>` where `Weak<>` itself is enough as may remain unlinked with `Arc` instance by default (`Weak::new()`) and `.upgrade()` would return `None` in such case.
This will in future reduce unnecessary code to address anything related to `parent` field of the `Process` structure.
> [#42] process: Reduce indirection of parent field in Process

- Documentation/compatibility.md
- kernel/process/process.rs
- kernel/syscalls/getppid.rs
- kernel/syscalls/mod.rs
Fixes #41 by adding the implementation of the `getppid` system call.
> [#41] process: Implementation of `getppid` syscall

- kernel/drivers/virtio/virtio_net.rs
- kernel/interrupt.rs
As discussed in #35 - net::process_packets() must be called in handler.
> move net::process_packets() call from interrupt::handle_irq to handler

- kernel/fs/inode.rs
- kernel/fs/mount.rs
- kernel/fs/opened_file.rs
- kernel/process/process.rs
- kernel/syscalls/accept.rs
- kernel/syscalls/bind.rs
- kernel/syscalls/connect.rs
- kernel/syscalls/fcntl.rs
- kernel/syscalls/fstat.rs
- kernel/syscalls/fsync.rs
- kernel/syscalls/getdents64.rs
- kernel/syscalls/getpeername.rs
- kernel/syscalls/getsockname.rs
- kernel/syscalls/ioctl.rs
- kernel/syscalls/listen.rs
- kernel/syscalls/mmap.rs
- kernel/syscalls/poll.rs
- kernel/syscalls/read.rs
- kernel/syscalls/readlink.rs
- kernel/syscalls/recvfrom.rs
- kernel/syscalls/select.rs
- kernel/syscalls/sendto.rs
- kernel/syscalls/write.rs
- kernel/syscalls/writev.rs
The same OpenedFile can be accessed from multiple processes (from a forked processes) and
`Arc<SpinLock<OpenedFile>>` leads to a busy spin lock if, for example, read blocks.
Make its locking more fine-grained to prenvet the busy loop.
> Fix opened file locking

- kernel/arch/x64/lock.rs
- kernel/mm/global_allocator.rs
Print where the lock is being held on a dead lock:
```
[   0.327] WARN: DEAD LOCK: already locked from the following context
#1: ffff800000222c89  kerla::printk::capture_backtrace()+0x79
#2: ffff8000001ed69b  kerla::arch::x64::lock::SpinLock<T>::lock()+0x81b
#3: ffff80000014220b  kerla::syscalls::ioctl::<i...yscallHandler>::sys_ioctl()+0x16b
#4: ffff80000014cf08  kerla::syscalls::SyscallHandler::do_dispatch()+0x2928
#5: ffff800000149dbc  kerla::syscalls::SyscallHandler::dispatch()+0x1ac
#6: ffff8000001b7fdc  x64_handle_syscall()+0x9c
#7: ffff800000100235  syscall_entry()+0x3d
[   0.327] WARN: Tried to lock from:
[   0.327]     0: ffff800000222c0a  kerla::printk::backtrace()+0x1a
[   0.327]     1: ffff8000001ed589  kerla::arch::x64::lock::SpinLock<T>::lock()+0x709
[   0.327]     2: …
```
> spinlock: Improve the debug message on a dead lock

- Makefile
- kernel/arch/x64/interrupt.rs
- kernel/arch/x64/mod.rs
- kernel/main.rs
- kernel/printk.rs
- kernel/process/switch.rs
- kernel/test_runner.rs
- tools/run-unittests.sh
> Refactor context switching. NFCI

- kernel/lang_items.rs
To prevent recursive panicking.
> Call `arch::print_str()` directly on double panic

- kernel/interrupt.rs
Fixes #50 
In this PR we introduce struct IrqHandler. 
```rust
struct IrqHandler {
callback: Box<dyn FnMut() + Send + Sync>,
attached: bool,
}
```
Right now there is only one ancillary field - attached, which allows an "overwrite" check. But potentially opens the way to build something like  /proc/interrupts.
> Panic on irq_handler overwrite

- Documentation/compatibility.md
- kernel/process/process.rs
- kernel/syscalls/gettid.rs
- kernel/syscalls/mod.rs
This PR is about adding gettid syscall implementation.
Motivation: reduce noise (count of unimplemented system call warnings) in integration tests.
Since we do not have multiple threads per process we always return process ID (PID).
I am not sure if `Process.tid` and all machinery around it should be added in this PR, or in separate.
> Single thread gettid syscall implementation

- kernel/deferred_job.rs
- kernel/interrupt.rs
- kernel/main.rs
- kernel/net/mod.rs
Introduces deferred job, a mechanism similar to Linux's tasklet or Ruby on Rails' ActiveJob to run time-consuming but timing critical work such as network packet processing.
> Implement deferred job

- kernel/interrupt.rs
> Release IRQ_HANDLERS' lock before running deferred jobs

- Cargo.lock
- Cargo.toml
- Makefile
- kernel/Cargo.toml
- kernel/main.rs
- tools/generate-kexts-loader.py
You can now specify the list of enabled kernel extensions through `$KEXTS` environment variable.
> Generate the kernel extensions loader

- Makefile
- tools/run-qemu.py
Allow specifying extra QEMU options from the command-line.
> build: Add $(QEMU_ARGS) option

- Makefile
- kernel/fs/devfs/tty.rs
- kernel/lang_items.rs
- kernel/logger.rs
- runtime/bootinfo.rs
- runtime/lib.rs
- runtime/print.rs
- runtime/x64/boot.rs
- runtime/x64/bootinfo.rs
- runtime/x64/interrupt.rs
- runtime/x64/mod.rs
- runtime/x64/serial.rs
- tools/run-qemu.py
Allow redirecting kernel messages to the secondary serial port thorugh $(LOG_SERIAL):
```
$ make run LOG=trace LOG_SERIAL="chardev:uart1" QEMU_ARGS="-chardev file,id=uart1,path=/tmp/kerla-debug.log,logappend=on"
```
> Support the secondary serial port for kernel messages

- kernel/arch/x64/process.rs
- kernel/arch/x64/usermode.S
- kernel/main.rs
- kernel/process/process.rs
- kernel/syscalls/mod.rs
- runtime/lib.rs
- runtime/x64/gdt.rs
- runtime/x64/mod.rs
- runtime/x64/syscall.rs
> x64: Make SyscallFrame compatible with Linux's struct pt_regs

- kernel/process/process.rs
- kernel/process/signal.rs
- kernel/syscalls/mod.rs
- kernel/syscalls/rt_sigprocmask.rs
- libs/kerla_utils/bitmap.rs
This pull request adds rt_sigprocmask syscall handler (https://man7.org/linux/man-pages/man2/sigprocmask.2.html). 
Before adding signal filtering, I want to discuss the general approach. 
Things that bother me: 
I feel like the `how` argument should be an enum, but how to handle `EINVAL` in that case?
And the `length` argument doesn't make any sense to me. According to the manual, it is `sizeof(kernel_sigset_t)`, and according to kernel sources, `kernel_sigset_t` is 1024 bits. So it always, according to POSIX, should be 128 bytes, unless we will run on something exotic like PDP-6/10 or DSP. If you can point me to some document or discussion to make sense of it, I would be grateful. 
Also `set` and `oldset` are 1024 bits in length. I am using a slightly modified BitMap from kerla_utils, …
> rt_sigprocmask syscall implementation

- kernel/process/process.rs
- kernel/process/signal.rs
- kernel/syscalls/rt_sigprocmask.rs
This is #112 follow-up with two changes:
1. We missed this part: "It is not possible to block SIGKILL or SIGSTOP.  Attempts to do so are silently ignored." (https://man7.org/linux/man-pages/man2/sigprocmask.2.html) addressing that
2.  Fixing Clippy issue: 
```sh
error: redundant pattern matching, consider using `is_err()`
--> kernel/syscalls/rt_sigprocmask.rs:27:16
|
27 |         if let Err(_) = current_process().set_signal_mask(how, set, oldset, length) {
|         -------^^^^^^-------------------------------------------------------------- help: try this: `if current_process().set_signal_mask(how, set, oldset, length).is_err()`
|
= note: `-D clippy::redundant-pattern-matching` implied by `-D warnings`
```
which we introduced in #112
> #112 followup (bugfix and fix build)

- kernel/fs/inode.rs
- kernel/fs/opened_file.rs
- kernel/net/socket.rs
- kernel/net/tcp_socket.rs
- kernel/syscalls/mod.rs
- kernel/syscalls/shutdown.rs
Since smoltcp seems not to support the `shutdown(2)` behavior, this PR implements the system call by closing the socket regardless of `how`.
> Implement shutdown(2)

- Cargo.lock
- libs/kerla_utils/Cargo.toml
- libs/kerla_utils/bitmap_allocator.rs
- libs/kerla_utils/bump_allocator.rs
- libs/kerla_utils/lib.rs
- runtime/page_allocator.rs
Add `free_pages` and a new allocator supporting freeing pages `BitMapAllocator`.
This commit also introduces OwnedPages, which owns dynamically allocated
pages and will automatically frees the pages on drop.
> Support freeing pages

- tools/docker2initramfs.py
- tools/embed-symbol-table.py
- tools/inspect-init-in-docker-image.py
- tools/run-qemu.py
> Use yapf for formatting python scripts

- kernel/fs/mod.rs
- kernel/fs/procfs/metrics.rs
- kernel/fs/procfs/mod.rs
- kernel/main.rs
- kernel/net/tcp_socket.rs
- kernel/process/mod.rs
- kernel/process/process.rs
- kernel/user_buffer.rs
- libs/kerla_utils/bitmap_allocator.rs
- runtime/page_allocator.rs
/proc/metrics is a Kerla-specific feature which exposes some metrics in
the kernel, in the Prometheus format.
> Implement /proc/metrics

- kernel/arch/x64/process.rs
> x64: Fill an XSAVE area with zeroes

- kernel/net/mod.rs
- libs/virtio/transports/virtio_pci_legacy.rs
DHCP_CLIENT is not initialized when dhcp=off.
> net: Fix for dhcp=off

- runtime/x64/interrupt.rs
> x64: Dump some important registers on an unsupported exception

- Cargo.lock
- kernel/Cargo.toml
- kernel/lang_items.rs
- kernel/logger.rs
Boot2dump is a new tiny operating system written by me, which is specialized
for saving a crash dump. Once Kerla panics, it jumps into the boot2dump's boot code.
Boot2dump reads an ext4 filesytem in a virtio-blk device, saves the dump into a file
and then it resets the computer.
It's an already working mechanism in my deployment in DigitalOcean!
> Support saving kernel crash logs using boot2dump

- kernel/interrupt.rs
> Allow specifying multiple interrupt handlers for the same IRQ number

- Documentation/compatibility.md
- kernel/syscalls/kill.rs
- kernel/syscalls/mod.rs
- libs/kerla_utils/bitmap_allocator.rs
This pr implements the kill syscall in order to further linux compatibility, omitting permission checks as Linux capabilities need to be implemented to do so. 
> Implement kill system call

- kernel/process/process.rs
- runtime/lib.rs
Does what it says on the tin. We need to share signals setup **per process** across **threads** for #88 and #115.
> [Closes #107] Wrap `SpinLock<SignalDelivery>` in `Arc<>`

- kernel/fs/opened_file.rs
- kernel/process/process.rs
Part of preparation to support the whole `clone3()` syscall. This change allows _threads_ to keep access to the shared table of opened files (in #88 and #115), but for now it retains just cloning the table into new `Arc<SpinLock<>>` on `fork()`.
> [Closes #106] Hold `Arc<SpinLock<OpenedFileTable>>` instead of just `SpinLock<>`

- .github/workflows/ci.yml
- kernel/arch/x64/process.rs
- kernel/fs/mount.rs
- kernel/fs/opened_file.rs
- kernel/fs/path.rs
- kernel/main.rs
- kernel/net/mod.rs
- kernel/net/socket.rs
- kernel/net/tcp_socket.rs
- kernel/process/process.rs
- kernel/process/signal.rs
- kernel/syscalls/linkat.rs
- kernel/syscalls/mod.rs
- kernel/syscalls/open.rs
- kernel/syscalls/readlink.rs
- libs/kerla_utils/buddy_allocator.rs
- libs/kerla_utils/id_table.rs
- libs/kerla_utils/lib.rs
- libs/virtio/device.rs
- libs/virtio/transports/virtio_mmio.rs
- runtime/page_allocator.rs
- runtime/spinlock.rs
- runtime/x64/bootinfo.rs
- runtime/x64/interrupt.rs
- runtime/x64/paging.rs
- rust-toolchain.toml
- testing/Dockerfile
- testing/var/www/html/index.html
When I started hacking on kerla, the CI was failing due to unpinned crates being installed.  Rather than check what version CI used to be running, I bumped the rust nightly we use until it built the deps again, fixed the clippies, and then pinned those crates.
> Get CI testing working again and prevent future bit-rot
