nuta/kerla

initramfs/integration_tests/close_pipes_on_exit.test
kernel/fs/opened_file.rs
kernel/process/process.rs

Close opened files on exit

---

kernel/fs/devfs/mod.rs
kernel/fs/devfs/null.rs
kernel/fs/devfs/tty.rs
kernel/fs/initramfs.rs
kernel/fs/inode.rs
kernel/fs/opened_file.rs
kernel/fs/tmpfs.rs
kernel/net/tcp_socket.rs
kernel/net/udp_socket.rs
kernel/net/unix_socket.rs
kernel/pipe.rs
kernel/syscalls/read.rs
kernel/syscalls/write.rs
kernel/tty/pty.rs

Implement fmt::Debug for inode objects

---

kernel/arch/x64/address.rs
kernel/arch/x64/backtrace.rs

backtrace: Don't access unmapped addresses

---

Cargo.lock
kernel/Cargo.toml
kernel/arch/x64/boot.rs
kernel/arch/x64/mod.rs
kernel/arch/x64/serial.rs
kernel/arch/x64/vga.rs

For debugging purpose. The serial port is still the input device for `/dev/console`.
Closes #62

Implement VGA console

---

kernel/arch/x64/mod.rs
kernel/arch/x64/profile.rs
kernel/boot.rs
kernel/main.rs
kernel/profile.rs

Implement boot time profiling

---

.github/workflows/release.yml

ci: Automate releases

---

kernel/Cargo.toml
libs/kerla_utils/Cargo.toml
runtime/Cargo.toml

Use Rust 2021 edition

---

exts/virtio_net/lib.rs
libs/kerla_api/driver/mod.rs
libs/kerla_api/driver/net.rs
tools/run-qemu.py

This will be useful when implementing new drivers.

Make driver trait available globally for other drivers and typo fix

---

kernel/fs/initramfs.rs
kernel/fs/stat.rs

initramfs: Implement file size

---

kernel/process/process.rs
kernel/syscalls/exit_group.rs
kernel/syscalls/mod.rs

Implement exit_group(2) syscall

---

kernel/main.rs
kernel/net/mod.rs
libs/kerla_api/driver/mod.rs
libs/kerla_api/driver/pci.rs
libs/kerla_api/kernel_ops.rs
runtime/bootinfo.rs
runtime/x64/bootinfo.rs

These cmdline parameters are used for running Kerla on DigitalOcean.

Make network parameters and allowed PCI devices configurable via cmdline

---

Makefile
testing/Dockerfile

build: Allow specifying extra kernel parameters through $(CMDLINE)

---

kernel/fs/tmpfs.rs
libs/kerla_utils/downcast.rs

downcast: Take a reference instead of the ownership

---

libs/virtio/device.rs

virtio: Fix a bug in used descriptors GC

---

kernel/net/tcp_socket.rs

net: Fix a memory leak

---

kernel/fs/procfs/metrics.rs

/proc/metrics: Expose the monotonic clock

---

kernel/arch/x64/process.rs
libs/virtio/device.rs
runtime/page_allocator.rs

allocator: Fill allocated pages with zeroes by default

---

kernel/arch/x64/process.rs
kernel/process/process.rs

x64: Fix memory leaks in a process internal buffers

---

.github/workflows/ci.yml
Cargo.lock
Documentation/SUMMARY.md
Documentation/compatibility.md
Documentation/environments/README.md
Documentation/environments/digitalocean.md
Documentation/hacking/README.md
Documentation/hacking/debugging-101.md
Documentation/kernel-parameters.md
Documentation/logging.md
Documentation/quickstart.md
Makefile
exts/virtio_net/lib.rs
kernel/Cargo.toml
kernel/arch/x64/process.rs
kernel/fs/procfs/metrics.rs
kernel/lang_items.rs
kernel/logger.rs
kernel/net/mod.rs
kernel/process/process.rs
libs/virtio/device.rs
libs/virtio/transports/mod.rs
libs/virtio/transports/virtio_mmio.rs
libs/virtio/transports/virtio_pci_legacy.rs
libs/virtio/transports/virtio_pci_modern.rs
runtime/page_allocator.rs
runtime/x64/interrupt.rs
testing/Dockerfile
tools/create-qcow2.sh

testing: Refactor Dockerfile

---

Cargo.lock
kernel/Cargo.toml
kernel/arch/x64/mod.rs
kernel/main.rs
kernel/mm/vm.rs
libs/kerla_api/Cargo.toml
libs/kerla_utils/lib.rs
runtime/Cargo.toml
runtime/backtrace.rs
runtime/lib.rs
runtime/spinlock.rs
runtime/x64/idle.rs
runtime/x64/mod.rs

Some assembly macros are now stabilized. This is a bug fix to follow the change. NFCI.

Fixes for Rust's stabilized features
